spring.application.name=UCOrm

# ??i ti?n t? c?u hình sang Google Gen AI chu?n c?a Spring AI
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_AI_GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash